name = "tightrope-web"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "tightrope_db"
database_id = "849aed27-56e2-40c2-aa64-a74bf50e8a63"

[[kv_namespaces]]
binding = "KV"
id = "ef945a9ece9843af8883df16be6676d7"

[[r2_buckets]]
binding = "ARCHIVE"
bucket_name = "tightrope-archive"

[vars]
ENVIRONMENT = "production"

# Preview environment (used by `wrangler pages dev`).
[env.preview]
name = "tightrope-web-preview"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "tightrope_db"
database_id = "fbb49bbf-f79b-4314-a976-2569559d239b"

[[env.preview.kv_namespaces]]
binding = "KV"
id = "18ca493dd5c44220b41328d488c3b54f"

[[env.preview.r2_buckets]]
binding = "ARCHIVE"
bucket_name = "tightrope-archive-preview"
