import type { Env } from "../env.js";

export interface PurgeResult {
  dryRun: boolean;
  cutoff: string;
  headlineDeleted: number;
  pillarDeleted: number;
  observationsDeleted: number;
}

/**
 * Delete the seeded synthetic history generated by `db/seed/generate.ts`.
 *
 * Target rows — all produced by the seed script, none written by real
 * ingestion:
 *
 *   - `headline_scores` before today (UTC) — the 90-day smoothed
 *     pseudo-random headline curve the seed emits.
 *   - `pillar_scores` before today (UTC) — the matching per-pillar curves.
 *   - `indicator_observations` whose `payload_hash` begins with `seed` —
 *     the 30-day `± 1.5 %` drift rows plus the single current-day calibrated
 *     rows that the seed inserts at first deploy. Live adapters use a
 *     content-derived hash, never one starting with `seed`, so the filter
 *     is unambiguous.
 *
 * Retained:
 *   - Today's real headline/pillar rows (the 5-minute recompute output).
 *   - Any live-ingested indicator observations (non-seed payload_hash).
 *   - The audit log, delivery commitments, timeline, KV caches (KV caches
 *     are invalidated so the next read reflects the smaller table).
 *
 * Dry-run by default — the caller must set `dryRun: false` to actually
 * delete. The return value reports row counts either way so operators
 * can review the scope before committing.
 *
 * This operation is destructive and irreversible short of restoring a D1
 * backup. Intended to be invoked once, immediately after shipping the
 * backfill pipeline, to remove the seed curve that was dressed up as real
 * history.
 */
export async function purgeSyntheticHistory(
  env: Env,
  opts: { dryRun: boolean },
): Promise<PurgeResult> {
  const now = new Date();
  const cutoff = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()),
  ).toISOString();

  const [hCount, pCount, oCount] = await Promise.all([
    env.DB
      .prepare("SELECT COUNT(*) AS n FROM headline_scores WHERE observed_at < ?")
      .bind(cutoff)
      .first<{ n: number }>(),
    env.DB
      .prepare("SELECT COUNT(*) AS n FROM pillar_scores WHERE observed_at < ?")
      .bind(cutoff)
      .first<{ n: number }>(),
    env.DB
      .prepare("SELECT COUNT(*) AS n FROM indicator_observations WHERE payload_hash LIKE 'seed%'")
      .first<{ n: number }>(),
  ]);

  const result: PurgeResult = {
    dryRun: opts.dryRun,
    cutoff,
    headlineDeleted: hCount?.n ?? 0,
    pillarDeleted: pCount?.n ?? 0,
    observationsDeleted: oCount?.n ?? 0,
  };

  if (opts.dryRun) return result;

  await env.DB.batch([
    env.DB.prepare("DELETE FROM headline_scores WHERE observed_at < ?").bind(cutoff),
    env.DB.prepare("DELETE FROM pillar_scores WHERE observed_at < ?").bind(cutoff),
    env.DB.prepare("DELETE FROM indicator_observations WHERE payload_hash LIKE 'seed%'"),
  ]);

  await Promise.all([
    env.KV.delete("score:latest").catch(() => undefined),
    env.KV.delete("score:history:90d").catch(() => undefined),
  ]);

  return result;
}
