/**
 * Generate seed SQL for a fresh D1 instance.
 *
 * Run: `pnpm tsx db/seed/generate.ts > db/seed/seed.sql`
 *
 * Produces:
 *  - 90-day headline & pillar score history terminating at high-good targets
 *    (roughly headline 31, market 22, fiscal 39, labour 28, delivery 46)
 *  - Current raw indicator observations for every defined indicator
 *  - Delivery commitments (matching the mockup)
 *  - Timeline events (matching the mockup, extended 18 months)
 *  - Today movements for the moved-today strip
 *  - An initial empty corrections log
 *
 * This seed is what makes the site live on first deploy. Ingestion workers
 * overwrite these rows with real data on their first successful run.
 */

import {
  PILLARS,
  PILLAR_ORDER,
  INDICATORS,
  CURRENT_SEED_VALUES,
  DELIVERY_COMMITMENTS_SEED,
  type PillarId,
  bandFor,
} from "../../packages/shared/src/index.js";

const TODAY = new Date("2026-04-17T14:02:00Z");
const ISO = (d: Date) => d.toISOString();
const addDays = (d: Date, n: number) => new Date(d.getTime() + n * 86400000);

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

// Deterministic pseudo-random in [-1, 1]
function prand(i: number): number {
  const x = Math.sin(i * 12.9898 + 78.233) * 43758.5453;
  return ((x - Math.floor(x)) * 2) - 1;
}

// Build a 90-day score history that smoothly lands on the target values.
function buildSeries(target: number, start: number, days: number, noise: number): number[] {
  const out: number[] = [];
  for (let i = 0; i < days; i++) {
    const t = i / (days - 1);
    const ease = 1 - (1 - t) * (1 - t);
    const base = start + (target - start) * ease;
    const n = noise * prand(i * 7 + Math.round(target));
    out.push(Math.max(0, Math.min(100, base + n)));
  }
  return out;
}

const PILLAR_TARGETS: Record<PillarId, { target: number; start: number }> = {
  market:   { target: 22, start: 54 },
  fiscal:   { target: 39, start: 48 },
  labour:   { target: 28, start: 32 },
  delivery: { target: 46, start: 52 },
};

// Generate the pillar series
const pillarSeries: Record<PillarId, number[]> = {
  market:   buildSeries(PILLAR_TARGETS.market.target,   PILLAR_TARGETS.market.start,   90, 2.4),
  fiscal:   buildSeries(PILLAR_TARGETS.fiscal.target,   PILLAR_TARGETS.fiscal.start,   90, 1.8),
  labour:   buildSeries(PILLAR_TARGETS.labour.target,   PILLAR_TARGETS.labour.start,   90, 1.4),
  delivery: buildSeries(PILLAR_TARGETS.delivery.target, PILLAR_TARGETS.delivery.start, 90, 1.6),
};

// Headline is geometric mean of pillars, recomputed per day so the displayed
// sparkline is internally consistent with the displayed pillars.
function geoMean(values: number[], weights: number[]): number {
  const EPS = 1e-6;
  let logSum = 0;
  let ws = 0;
  for (let i = 0; i < values.length; i++) {
    const v = values[i]!;
    const w = weights[i]!;
    logSum += w * Math.log(v + EPS);
    ws += w;
  }
  return Math.exp(logSum / ws) - EPS;
}

const pillarWeights = PILLAR_ORDER.map((p) => PILLARS[p].weight);

const headlineSeries: number[] = [];
for (let i = 0; i < 90; i++) {
  const values = PILLAR_ORDER.map((p) => pillarSeries[p][i]!);
  headlineSeries.push(geoMean(values, pillarWeights));
}

function editorialFor(dominant: PillarId, dir: "improving" | "worsening" | "broadly unchanged", delta: number): string {
  const def = PILLARS[dominant];
  const sign = delta > 0 ? "up" : delta < 0 ? "down" : "flat";
  const mag = Math.abs(delta).toFixed(1);
  return `${def.title} is the biggest drag; the score is ${dir} (${sign} ${mag} on the week).`;
}

// ---------- emit SQL ----------

const out: string[] = [];
out.push("-- Tightrope Tracker seed -- generated by db/seed/generate.ts");
out.push("-- Do not edit by hand. Regenerate with: pnpm tsx db/seed/generate.ts > db/seed/seed.sql");
out.push("-- D1 wraps executions in a DO transaction automatically -- do not emit BEGIN/COMMIT here.");
out.push("");

// Clear existing rows for idempotent reseeding.
out.push("DELETE FROM indicator_observations;");
out.push("DELETE FROM pillar_scores;");
out.push("DELETE FROM headline_scores;");
out.push("DELETE FROM delivery_commitments;");
out.push("DELETE FROM timeline_events;");
out.push("DELETE FROM today_movements;");
out.push("DELETE FROM ingestion_audit;");
out.push("");

// Headline + pillar history (90 days).
for (let i = 0; i < 90; i++) {
  const day = addDays(TODAY, i - 89);
  const iso = ISO(day);
  for (const p of PILLAR_ORDER) {
    const v = pillarSeries[p][i]!;
    const band = bandFor(v).id;
    out.push(
      `INSERT INTO pillar_scores (pillar_id, observed_at, value, band) VALUES ('${p}', '${iso}', ${v.toFixed(3)}, '${band}');`,
    );
  }
  const h = headlineSeries[i]!;
  const band = bandFor(h).id;
  // Pick biggest drag by weighted shortfall from 100 at each day.
  let dom: PillarId = "market";
  let best = -1;
  for (const p of PILLAR_ORDER) {
    const impact = (100 - pillarSeries[p][i]!) * PILLARS[p].weight;
    if (impact > best) { best = impact; dom = p; }
  }
  const prev7 = i > 7 ? headlineSeries[i - 7]! : h;
  const delta7 = h - prev7;
  const dir: "improving" | "worsening" | "broadly unchanged" =
    Math.abs(delta7) < 0.3 ? "broadly unchanged" : delta7 > 0 ? "improving" : "worsening";
  const ed = editorialFor(dom, dir, delta7);
  out.push(
    `INSERT INTO headline_scores (observed_at, value, band, dominant, editorial) VALUES ('${iso}', ${h.toFixed(3)}, '${band}', '${dom}', '${esc(ed)}');`,
  );
}
out.push("");

// Current indicator observations (one per indicator). The hand-calibrated
// starting values live in `packages/shared/src/seedValues.ts` and are
// validated by `seedValues.test.ts` to be (a) complete and (b) within each
// indicator's plausible magnitude range (so a MoM-% value can't leak into an
// index-scale indicator again).
const currentValues = CURRENT_SEED_VALUES;

for (const id of Object.keys(INDICATORS)) {
  const def = INDICATORS[id]!;
  const value = currentValues[id];
  if (value === undefined) throw new Error(`missing seed value for indicator ${id}`);
  const hash = `seed_${id}`;
  out.push(
    `INSERT INTO indicator_observations (indicator_id, observed_at, value, source_id, payload_hash) VALUES ('${id}', '${ISO(TODAY)}', ${value}, '${def.sourceId}', '${hash}');`,
  );
  // Also seed 30 daily prior observations for sparklines.
  for (let k = 29; k >= 1; k--) {
    const day = addDays(TODAY, -k);
    const drift = value * (1 + 0.015 * prand(k + id.length));
    out.push(
      `INSERT INTO indicator_observations (indicator_id, observed_at, value, source_id, payload_hash) VALUES ('${id}', '${ISO(day)}', ${drift.toFixed(4)}, '${def.sourceId}', '${hash}_h${k}');`,
    );
  }
}
out.push("");

// Delivery commitments are owned by the shared package so web, api, and
// the ingest writer all see the same contract. The seed generator just
// formats each row as SQL — the canonical data and invariants live in
// packages/shared/src/deliveryCommitmentsSeed.ts, tested in
// deliveryCommitmentsSeed.test.ts.
for (const d of DELIVERY_COMMITMENTS_SEED) {
  out.push(
    `INSERT INTO delivery_commitments (id, name, department, latest, target, status, source_url, source_label, notes, updated_at, sort_order) VALUES ('${esc(d.id)}', '${esc(d.name)}', '${esc(d.department)}', '${esc(d.latest)}', '${esc(d.target)}', '${esc(d.status)}', '${esc(d.sourceUrl)}', '${esc(d.sourceLabel)}', '${esc(d.notes)}', '${ISO(TODAY)}', ${d.sortOrder});`,
  );
}
out.push("");

// Timeline events from the mockup, extended backwards ~18 months. Every
// row now carries a sourceUrl pointing at the primary source the reader
// can open to verify. Where a deep URL is not confidently available
// (for instance a specific MPC meeting page), we link to the durable
// BoE / OBR / gov.uk section that aggregates the series — never a news
// aggregator. Tested in packages/shared/src/timelineSeed.test.ts.
type TLRow = { id: string; date: string; title: string; summary: string; category: string; sourceLabel: string; sourceUrl: string };
const timeline: TLRow[] = [
  {
    id: "t_2026_04_22", date: "2026-04-22",
    title: "March CPI rises to 3.3%, BoE path under scrutiny",
    summary: "ONS releases March 2026 CPI inflation data showing headline CPI at 3.3% YoY (up from ~3.0% in February), driven by lingering energy and petrol price effects from the Iran conflict period. Markets price in a more cautious BoE path ahead of the 30 April MPC decision; gilt yields stabilise but remain elevated.",
    category: "fiscal", sourceLabel: "ONS Consumer price inflation",
    sourceUrl: "https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest",
  },
  {
    id: "t_2026_04_21", date: "2026-04-21",
    title: "Resolution Foundation: conflict could erase £16bn of headroom",
    summary: "Resolution Foundation warns that a prolonged or severe Middle East conflict could erase up to £16bn of the Chancellor's current-budget headroom — almost three-quarters of the March OBR cushion — via higher energy prices, inflation, and debt interest. Report highlights fiscal vulnerability even under the current ceasefire.",
    category: "fiscal", sourceLabel: "Resolution Foundation",
    sourceUrl: "https://www.resolutionfoundation.org/publications/",
  },
  {
    id: "t_2026_04_08", date: "2026-04-08",
    title: "US, Israel and Iran agree conditional ceasefire",
    summary: "US, Israel and Iran agree a conditional two-week ceasefire; UK Foreign Secretary and international finance ministers welcome the de-escalation, citing restored Strait of Hormuz shipping and falling oil and gas prices. Initial market relief begins, setting the stage for sterling's recovery to pre-war levels by 17 April.",
    category: "geopolitical", sourceLabel: "Foreign Office / gov.uk",
    sourceUrl: "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office",
  },
  {
    id: "t_2026_04_17", date: "2026-04-17",
    title: "Sterling recovers to pre-war levels",
    summary: "GBP/USD back near 1.2400 as the Iran ceasefire holds and Strait of Hormuz shipping normalises. Oil and UK gas sell off sharply. BoE officials nonetheless stress inflation control remains the priority.",
    category: "market", sourceLabel: "Bank of England exchange rates",
    sourceUrl: "https://www.bankofengland.co.uk/statistics/exchange-rates",
  },
  {
    id: "t_2026_04_16", date: "2026-04-16",
    title: "Reeves rules out tax rises or borrowing for extra defence spending",
    summary: "Chancellor tells reporters additional defence outlays up to the 3.5% commitment will not be funded by more borrowing or higher taxes, pointing the pressure back at welfare and departmental restraint.",
    category: "fiscal", sourceLabel: "HM Treasury news",
    sourceUrl: "https://www.gov.uk/government/organisations/hm-treasury",
  },
  {
    id: "t_2026_03_03", date: "2026-03-03",
    title: "OBR Spring Forecast: headroom 23.6bn, GDP cut to 1.1%",
    summary: "Current-budget headroom ticks up from 22.0bn at the November Budget. 2026 growth downgraded from 1.4%. IMF subsequently cuts to 0.8% citing the Middle East shock.",
    category: "fiscal", sourceLabel: "OBR EFO",
    sourceUrl: "https://obr.uk/efo/",
  },
  {
    id: "t_2026_02_28", date: "2026-02-28",
    title: "Iran conflict begins, energy shock lands",
    summary: "UK natural gas front-month jumps 38% inside a week. 30y gilts break 5.5% for the first time since 1998. Tightrope Score moves from 51 to 68 over four trading sessions.",
    category: "geopolitical", sourceLabel: "BoE markets",
    sourceUrl: "https://www.bankofengland.co.uk/markets",
  },
  {
    id: "t_2025_12_18", date: "2025-12-18",
    title: "Planning & Infrastructure Bill receives Royal Assent",
    summary: "Landmark reform of the planning system passes both houses with cross-bench support; commencement orders expected by late spring.",
    category: "delivery", sourceLabel: "Planning & Infrastructure Act 2025",
    sourceUrl: "https://www.legislation.gov.uk/ukpga/2025/34/enacted",
  },
  {
    id: "t_2026_02_12", date: "2026-02-12",
    title: "BoE cuts Bank Rate to 3.75%",
    summary: "7-2 vote. MPC minutes emphasise inflation persistence; markets trim the 2026 cut path.",
    category: "monetary", sourceLabel: "BoE MPC minutes",
    sourceUrl: "https://www.bankofengland.co.uk/monetary-policy-summary-and-minutes",
  },
  {
    id: "t_2025_11", date: "2025-11-26",
    title: "Autumn Budget: 22.0bn headroom restored",
    summary: "Combination of receipts upgrade and tighter departmental envelope rebuilds the cushion after the March 2025 crunch (9.9bn).",
    category: "fiscal", sourceLabel: "HM Treasury",
    sourceUrl: "https://www.gov.uk/government/organisations/hm-treasury",
  },
  {
    id: "t_2025_09", date: "2025-09-18",
    title: "BoE holds Bank Rate at 4.00%, starts reducing gilt sales",
    summary: "QT pace pared back; MPC cites technical market conditions rather than policy loosening.",
    category: "monetary", sourceLabel: "BoE MPC minutes",
    sourceUrl: "https://www.bankofengland.co.uk/monetary-policy-summary-and-minutes",
  },
  {
    id: "t_2025_06", date: "2025-06-10",
    title: "Industrial Strategy white paper published",
    summary: "Sets out eight priority sectors and the British Industrial Competitiveness Scheme framework.",
    category: "policy", sourceLabel: "DBT",
    sourceUrl: "https://www.gov.uk/government/organisations/department-for-business-and-trade",
  },
  {
    id: "t_2025_03", date: "2025-03-26",
    title: "OBR Spring Forecast: headroom collapses to 9.9bn",
    summary: "The crunch. Gilts reprice and the Chancellor promises restoration in the next fiscal event.",
    category: "fiscal", sourceLabel: "OBR EFO",
    sourceUrl: "https://obr.uk/efo/",
  },
  {
    id: "t_2024_10", date: "2024-10-30",
    title: "First Reeves Budget: 22.0bn headroom set",
    summary: "Opening fiscal envelope. Employer NICs rise, capital budgets reprioritised toward infrastructure.",
    category: "fiscal", sourceLabel: "HM Treasury",
    sourceUrl: "https://www.gov.uk/government/organisations/hm-treasury",
  },
];
for (const t of timeline) {
  out.push(
    `INSERT INTO timeline_events (id, event_date, title, summary, category, source_label, source_url) VALUES ('${esc(t.id)}', '${esc(t.date)}', '${esc(t.title)}', '${esc(t.summary)}', '${esc(t.category)}', '${esc(t.sourceLabel)}', '${esc(t.sourceUrl)}');`,
  );
}
out.push("");

// Today movements matching the mockup.
type MovementRow = {
  indicatorId: string; label: string; latest: number; display: string;
  change: number; changePct: number; changeDisplay: string;
  direction: "up" | "down" | "flat"; worsening: 0 | 1;
  sparkline: number[]; gloss: string;
};
const movements: MovementRow[] = [
  {
    indicatorId: "gilt_10y", label: "10y gilt", latest: 4.78, display: "4.78%",
    change: 0.06, changePct: 1.27, changeDisplay: "+6 bp", direction: "up", worsening: 1,
    sparkline: [4.70, 4.71, 4.72, 4.73, 4.74, 4.74, 4.76, 4.78],
    gloss: "Above the 4.7% MPC comfort zone.",
  },
  {
    indicatorId: "gilt_30y", label: "20y gilt", latest: 5.73, display: "5.73%",
    change: 0.09, changePct: 1.60, changeDisplay: "+9 bp", direction: "up", worsening: 1,
    sparkline: [5.58, 5.60, 5.62, 5.65, 5.68, 5.70, 5.71, 5.73],
    gloss: "Fresh multi-decade high.",
  },
  {
    indicatorId: "gbp_usd", label: "GBP / USD", latest: 1.2418, display: "1.2418",
    change: -0.0042, changePct: -0.34, changeDisplay: "-0.34%", direction: "down", worsening: 1,
    sparkline: [1.2475, 1.2460, 1.2450, 1.2440, 1.2430, 1.2425, 1.2420, 1.2418],
    gloss: "Off pre-war highs, BoE dovish repricing.",
  },
  {
    indicatorId: "ftse_250", label: "FTSE 250", latest: 22984, display: "22,984",
    change: 312, changePct: 1.38, changeDisplay: "+1.38%", direction: "up", worsening: 0,
    sparkline: [22100, 22280, 22450, 22580, 22700, 22810, 22900, 22984],
    gloss: "Post-tariff recovery extends.",
  },
];
for (const m of movements) {
  const spark = JSON.stringify(m.sparkline);
  out.push(
    `INSERT INTO today_movements (indicator_id, label, latest_value, display_value, change, change_pct, change_display, direction, worsening, sparkline, gloss, observed_at) VALUES ('${esc(m.indicatorId)}', '${esc(m.label)}', ${m.latest}, '${esc(m.display)}', ${m.change}, ${m.changePct}, '${esc(m.changeDisplay)}', '${esc(m.direction)}', ${m.worsening}, '${esc(spark)}', '${esc(m.gloss)}', '${ISO(TODAY)}');`,
  );
}
out.push("");

// Seed a successful "initial_seed" audit entry so the methodology page has something to show.
out.push(
  `INSERT INTO ingestion_audit (id, source_id, started_at, completed_at, status, rows_written, source_url) VALUES ('seed_0001', 'seed', '${ISO(TODAY)}', '${ISO(TODAY)}', 'success', ${Object.keys(INDICATORS).length}, 'local://seed');`,
);

out.push("");

process.stdout.write(out.join("\n"));
