import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const SEED_PATH = resolve(HERE, "../../..", "db", "seed", "seed.sql");

/**
 * Guards against regressions in the generated seed file. Unlike the
 * per-module unit tests, this exercises the *artifact* the D1 database
 * actually ingests on `pnpm seed`. If the generator regresses (e.g.
 * emits NULL source URLs, or an operator edits seed.sql by hand and
 * drops a field), this file surfaces it before the first deploy.
 *
 * The seed is regenerated by `pnpm tsx db/seed/generate.ts > db/seed/seed.sql`.
 * Generators live in db/seed/generate.ts; canonical tables live in
 * packages/shared/src/deliveryCommitmentsSeed.ts (+ helpers).
 */
function loadSeed(): string {
  return readFileSync(SEED_PATH, "utf8");
}

describe("seed.sql — invariants on shipped data", () => {
  it("every timeline_events INSERT has a non-NULL https sourceUrl", () => {
    // Audit H10: previously only 3 of 11 timeline rows had a URL. The
    // rest loaded as NULL, so the Timeline UI rendered "Source:
    // editorial" for most events. Every row must now link to a
    // primary source (BoE, OBR, gov.uk, parliament.uk).
    const seed = loadSeed();
    const timelineInserts = seed
      .split("\n")
      .filter((l) => l.startsWith("INSERT INTO timeline_events"));
    expect(timelineInserts.length, "timeline rows").toBeGreaterThan(0);
    for (const line of timelineInserts) {
      const tail = line.trimEnd().replace(/\);$/, "");
      expect(tail, line).not.toMatch(/,\s*NULL\s*$/);
      expect(tail, line).toMatch(/'https:\/\/[^']+'$/);
    }
  });

  it("every delivery_commitments INSERT has a non-empty notes field and https source_url", () => {
    const seed = loadSeed();
    const deliveryInserts = seed
      .split("\n")
      .filter((l) => l.startsWith("INSERT INTO delivery_commitments"));
    expect(deliveryInserts.length, "delivery rows").toBeGreaterThanOrEqual(8);
    for (const line of deliveryInserts) {
      // The INSERT layout is:
      //   VALUES ('id', 'name', 'department', 'latest', 'target',
      //           'status', 'source_url', 'source_label', 'notes',
      //           'updated_at', sort_order)
      // So the quoted strings (indexed 0-9) carry URL at index 6 and
      // notes at index 8. Use a SQL-aware regex that treats doubled
      // single quotes ('') as escaped-quote inside a string so
      // "project''s" stays a single token.
      const quoted = [...line.matchAll(/'((?:[^']|'')*)'/g)].map((m) => m[1]);
      expect(quoted.length, line).toBeGreaterThanOrEqual(10);
      const sourceUrl = quoted[6] ?? "";
      const notes = quoted[8] ?? "";
      expect(sourceUrl, `source_url: ${line.substring(0, 120)}`).toMatch(/^https:\/\//);
      expect(notes.length, `notes empty: ${line.substring(0, 120)}`).toBeGreaterThanOrEqual(40);
    }
  });
});
