/**
 * SEC-10: CSP nonce migration. Drop `'unsafe-inline'` from `script-src` and
 * replace it with a per-request nonce that every legitimate inline `<script>`
 * carries. The nonce must be:
 *   - cryptographically random (so an attacker injecting HTML cannot guess it),
 *   - unique per request (so a snapshot of one response can't be replayed
 *     against another user's request),
 *   - long enough that brute-forcing inside the request lifetime is hopeless.
 *
 * Style-src deliberately keeps `'unsafe-inline'` (every section uses
 * `style="..."` attributes; nonces don't apply to inline style attributes).
 */
import { describe, expect, it } from "vitest";
import { buildCsp, generateNonce } from "./csp.js";

describe("generateNonce", () => {
  it("returns a non-empty base64-style string at least 22 chars long (128 bits of entropy)", () => {
    const n = generateNonce();
    expect(typeof n).toBe("string");
    expect(n.length).toBeGreaterThanOrEqual(22);
    // base64 / base64url charset only — no whitespace, quotes, or angle brackets
    // that could escape the attribute context.
    expect(/^[A-Za-z0-9+/_=-]+$/.test(n)).toBe(true);
  });

  it("produces different values across calls (randomness, not a counter)", () => {
    const seen = new Set<string>();
    for (let i = 0; i < 64; i++) seen.add(generateNonce());
    // 64 random 128-bit nonces with zero collisions is overwhelmingly likely.
    expect(seen.size).toBe(64);
  });
});

describe("buildCsp", () => {
  const NONCE = "abc123XYZ_test_nonce";

  it("does NOT include 'unsafe-inline' in script-src — the whole point of SEC-10", () => {
    const csp = buildCsp({ nonce: NONCE, isEmbed: false });
    const scriptSrc = directive(csp, "script-src");
    expect(scriptSrc).not.toContain("'unsafe-inline'");
  });

  it("includes the per-request nonce as 'nonce-XXX' in script-src", () => {
    const csp = buildCsp({ nonce: NONCE, isEmbed: false });
    expect(directive(csp, "script-src")).toContain(`'nonce-${NONCE}'`);
  });

  it("retains 'self' and drops https://plausible.io from script-src (SEC-12 self-hosts it under /vendor)", () => {
    const csp = buildCsp({ nonce: NONCE, isEmbed: false });
    const s = directive(csp, "script-src");
    expect(s).toContain("'self'");
    // Plausible script is now served from /vendor/plausible.js; no need
    // for it in script-src. Events still POST to plausible.io via
    // connect-src (asserted below).
    expect(s).not.toContain("https://plausible.io");
  });

  it("retains https://plausible.io in connect-src so the analytics POST still works", () => {
    const csp = buildCsp({ nonce: NONCE, isEmbed: false });
    expect(directive(csp, "connect-src")).toContain("https://plausible.io");
  });

  it("retains 'unsafe-inline' in style-src (deliberate — style attributes are pervasive and harmless)", () => {
    const csp = buildCsp({ nonce: NONCE, isEmbed: false });
    expect(directive(csp, "style-src")).toContain("'unsafe-inline'");
  });

  it("uses strict frame-ancestors for the main site and permissive for /embed/", () => {
    const main = buildCsp({ nonce: NONCE, isEmbed: false });
    const embed = buildCsp({ nonce: NONCE, isEmbed: true });
    expect(directive(main, "frame-ancestors")).toContain("'self'");
    expect(directive(embed, "frame-ancestors")).toContain("*");
    expect(directive(main, "form-action")).toContain("'self'");
    expect(directive(embed, "form-action")).toContain("'none'");
  });

  it("retains the canonical safety directives (default-src, object-src, base-uri, etc.)", () => {
    const csp = buildCsp({ nonce: NONCE, isEmbed: false });
    expect(directive(csp, "default-src")).toContain("'self'");
    expect(directive(csp, "object-src")).toContain("'none'");
    expect(directive(csp, "base-uri")).toContain("'self'");
    expect(csp).toContain("upgrade-insecure-requests");
  });

  it("rejects pathological nonces that could break out of the attribute (defence in depth)", () => {
    // The nonce is generated by us, but make absolutely sure we never emit
    // a CSP whose nonce field could be fooled by HTML/CSP-syntax characters.
    const csp = buildCsp({ nonce: NONCE, isEmbed: false });
    expect(csp).not.toContain("nonce-'");
    expect(csp).not.toContain('"');
    // No newlines that could split the header into two:
    expect(csp).not.toContain("\n");
    expect(csp).not.toContain("\r");
  });
});

function directive(csp: string, name: string): string {
  const found = csp
    .split(";")
    .map((s) => s.trim())
    .find((s) => s.toLowerCase().startsWith(name.toLowerCase() + " ") || s.toLowerCase() === name.toLowerCase());
  if (!found) throw new Error(`directive ${name} not found in CSP: ${csp}`);
  return found;
}
